// All posts

export type Post = {
  id: number,
  number: string,
  slug: string,
  isLab: boolean,
  filename: string,
  date: string,
  coolness: number,
  difficulty: null | string,
  tags: Array<string>,
  tech: null | Array<string>,
  title: string,
  cover: string,
  description: string,
}

const posts: Array<Post> = [
  {
    id: 0,
    number: '000',
    slug: "test",
    isLab: true,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 5,
    difficulty: "hard",
    tags: ["fun", "experimental"],
    tech: ["Any Tech", "React"],
    title: "Zero The navigation system provides a set of screen elements.",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    id: 1,
    number: '001',
    slug: "test1",
    isLab: false,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 2,
    difficulty: null,
    tags: ["animation", "fun"],
    tech: null,
    title: "One The navigation system provides a set of screen elements.",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    id: 2,
    number: '002',
    slug: "test2",
    isLab: true,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 2,
    difficulty: "medium",
    tags: ["animation", "fun"],
    tech: ["Any Tech", "React", "Node", "AWS"],
    title: "Two The navigation system provides a set of screen elements.",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    id: 3,
    number: '003',
    slug: "test3",
    isLab: true,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 5,
    difficulty: "hard",
    tags: ["animation", "fun", "experimental"],
    tech: ["Any Tech", "React", "Sass"],
    title: "Three The navigation system provides a set of screen elements.",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    id: 4,
    number: '004',
    slug: "test4",
    isLab: false,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 2,
    difficulty: null,
    tags: ["animation"],
    tech: null,
    title: "Four The navigation system provides a set of screen elements.",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    id: 5,
    number: '005',
    slug: "test5",
    isLab: true,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 3,
    difficulty: "low",
    tags: ["animation"],
    tech: ["Any Tech", "React", "Sass", "NextJS"],
    title: "A new way to search for posts",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    id: 6,
    number: '006',
    slug: "test6",
    isLab: true,
    filename: "000-test",
    date: "Jul 23, 2020",
    coolness: 2,
    difficulty: "medium",
    tags: ["animation", "fun", "project"],
    tech: ["Any Tech", "NextJS"],
    title: "Six The navigation system provides a set of screen elements.",
    cover: "https://picsum.photos/1440/900",
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
]

export default posts
