// All posts

type Post = {
  id: number,
  number: string,
  slug: string,
  isLab: boolean,
  filename: string,
  date: string,
  coolness: number,
  tags: Array<string>,
  title: string,
  cover: string,
  description: string,
}

const posts: Array<Post> = [
  {
    "id": 0,
    "number": '000',
    "slug": "test",
    "isLab": true,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 5,
    "tags": ["animation", "fun", "experimental"],
    "title": "The navigation system provides a set of screen elements.",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    "id": 1,
    "number": '001',
    "slug": "test1",
    "isLab": false,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 2,
    "tags": ["animation", "fun"],
    "title": "The navigation system provides a set of screen elements.",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    "id": 2,
    "number": '002',
    "slug": "test2",
    "isLab": true,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 2,
    "tags": ["animation", "fun"],
    "title": "The navigation system provides a set of screen elements.",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    "id": 3,
    "number": '003',
    "slug": "test3",
    "isLab": true,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 5,
    "tags": ["animation", "fun", "experimental"],
    "title": "The navigation system provides a set of screen elements.",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    "id": 4,
    "number": '004',
    "slug": "test4",
    "isLab": false,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 2,
    "tags": ["animation", "fun"],
    "title": "The navigation system provides a set of screen elements.",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    "id": 5,
    "number": '005',
    "slug": "test5",
    "isLab": true,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 2,
    "tags": ["animation", "fun"],
    "title": "The navigation system provides a set of screen elements. Super really ultimate long",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
  {
    "id": 6,
    "number": '006',
    "slug": "test6",
    "isLab": true,
    "filename": "000-test",
    "date": "Jul 23, 2020",
    "coolness": 2,
    "tags": ["animation", "fun"],
    "title": "The navigation system provides a set of screen elements.",
    "cover": "https://picsum.photos/1440/900",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero placeat fuga rem illum molestias quae.",
  },
]

export default posts
