type Product = {
  id: number,
  slug: string,
  name: string,
  image: string,
  price: string,
  type: string,
}

const products: Array<Product> = [
  {
    id: 1,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 2,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 3,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 4,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 5,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 6,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 7,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 8,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 9,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 10,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 11,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
  {
    id: 12,
    slug: 'ribcage-shirt',
    name: 'Ribcage Shirt',
    image: 'ribcage-shirt.png',
    price: '32',
    type: 'shirt',
  },
]

export default products
