export type Product = {
  id: number,
  slug: string,
  name: string,
  image: string,
  price: string,
  type: string,
}

const products: Array<Product> = [
  {
    id: 1,
    slug: 'empty-shirt-women',
    name: 'Empty Shirt (Women)',
    image: 'empty-shirt-women.jpg',
    price: '50',
    type: 'shirt',
  },
  {
    id: 2,
    slug: 'empty-shirt-men',
    name: 'Empty Shirt (Men)',
    image: 'empty-shirt-men.jpg',
    price: '50',
    type: 'shirt',
  },
  {
    id: 3,
    slug: 'ribcage-shirt-women',
    name: 'Ribcage Shirt (Women)',
    image: 'ribcage-shirt-women.jpg',
    price: '50',
    type: 'shirt',
  },
  {
    id: 4,
    slug: 'ribcage-shirt-men',
    name: 'Ribcage Shirt (Men)',
    image: 'ribcage-shirt-men.png',
    price: '50',
    type: 'shirt',
  },
  {
    id: 5,
    slug: 'sacred-geometry-women',
    name: 'Sacred Geometry Shirt (Women)',
    image: 'sacred-geometry-women.png',
    price: '50',
    type: 'shirt',
  },
  {
    id: 6,
    slug: 'sacred-geometry-men',
    name: 'Sacred Geometry Shirt (Men)',
    image: 'sacred-geometry-men.png',
    price: '50',
    type: 'shirt',
  },
  {
    id: 7,
    slug: 'logo-jacket',
    name: 'Logo Jacket',
    image: 'logo-jacket.png',
    price: '60',
    type: 'jacket',
  },
  {
    id: 8,
    slug: 'logo-hoodie',
    name: 'Logo Hoodie',
    image: 'logo-hoodie.png',
    price: '40',
    type: 'sweater',
  },
  {
    id: 9,
    slug: 'logo-shirt',
    name: 'Logo Shirt',
    image: 'logo-shirt.png',
    price: '25',
    type: 'shirt',
  },
  {
    id: 10,
    slug: 'logo-touque',
    name: 'Logo Touque',
    image: 'logo-touque.png',
    price: '25',
    type: 'hat',
  },
  {
    id: 11,
    slug: 'logo-baseball-hat',
    name: 'Logo Baseball Hat',
    image: 'logo-baseball-hat.png',
    price: '25',
    type: 'hat',
  },
  {
    id: 12,
    slug: 'logo-sticker',
    name: 'Logo Sticker',
    image: 'logo-sticker.png',
    price: '3.50',
    type: 'sticker',
  },
]

export default products
